services:
  - type: web
    name: yt-loop
    env: python
    plan: free
    buildCommand: |
      # create bin and download static ffmpeg (johnvansickle build)
      mkdir -p bin
      curl -L -o /tmp/ffmpeg.tar.xz "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"
      tar -xJf /tmp/ffmpeg.tar.xz --strip-components=1 -C bin
      chmod +x bin/ffmpeg
    startCommand: python main.py
    envVars:
      - key: YT_STREAM_KEY
        sync: false
      - key: VIDEO_URL
        sync: false
      - key: BITRATE
        sync: false
